# Warning: This file should only be used if the endpoints are not yet ready to be public, or not suitable for public consumption (like the data plane endpoints).
# In most cases, you shouldn't need to add the endpoints here.
# Only add endpoints here when it is an explicit requirement, or if you know what you are doing.
# There should be no duplicated endpoints or schemas in these 2 files. They should only defined in one of them.
openapi: 3.0.0
info:
  title: Managed Service API
  version: 0.0.1
  description: Managed Service API
servers:
  - url: https://api.openshift.com
    description: Main (production) server
  - url: https://api.stage.openshift.com
    description: Staging server
  - url: http://localhost:8000
    description: localhost
  - url: /
    description: current domain
paths:
  #
  # These are the connector related APIs
  #
  '/api/managed-services-api/v1/connector-types/{id}':
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectorType'
          description: The connector type matching the request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
          description: Auth token is invalid
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                404Example:
                  $ref: '#/components/examples/404Example'
          description: No matching connector type exists
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500Example:
                  $ref: '#/components/examples/500Example'
          description: Unexpected error occurred
      security:
        - Bearer: [ ]
      operationId: getConnectorTypeByID
      summary: Get a connector type by name and version
    parameters:
      - $ref: "#/components/parameters/id"

  /api/managed-services-api/v1/connector-types:
    get:
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectorTypeList'
          description: A list of connector types
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
          description: Auth token is invalid
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500Example:
                  $ref: '#/components/examples/500Example'
          description: Unexpected error occurred
      security:
        - Bearer: [ ]
      operationId: listConnectorTypes
      summary: Returns a list of connector types
  /api/managed-services-api/v1/kafkas/{id}/connector-deployments:
    post:
      operationId: createConnector
      parameters:
        - in: query
          name: async
          description: Perform the action in an asynchronous manner
          schema:
            type: boolean
          required: true
      requestBody:
        description: Connector data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connector'
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Connector'
          description: Accepted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                400CreationExample:
                  $ref: '#/components/examples/400CreationExample'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
          description: Auth token is invalid
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                404Example:
                  $ref: '#/components/examples/404Example'
          description: The requested resource doesn't exist
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500Example:
                  $ref: '#/components/examples/500Example'
          description: An unexpected error occurred creating the connector
      security:
        - Bearer: [ ]
      summary: Create a new connector
    get:
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectorList'
          description: A list of connector deployments
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
          description: Auth token is invalid
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500Example:
                  $ref: '#/components/examples/500Example'
          description: Unexpected error occurred
      security:
        - Bearer: [ ]
      operationId: listConnectors
      summary: Returns a list of connector types
    parameters:
      - $ref: "#/components/parameters/id"
  '/api/managed-services-api/v1/kafkas/{id}/connector-deployments/{cid}':
    get:
      parameters:
        - $ref: "#/components/parameters/id"
        - name: cid
          description: The id of the connector
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Connector'
          description: The connector deployment matching the request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
          description: Auth token is invalid
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                404Example:
                  $ref: '#/components/examples/404Example'
          description: No matching connector type exists
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500Example:
                  $ref: '#/components/examples/500Example'
          description: Unexpected error occurred
      security:
        - Bearer: [ ]
      operationId: getConnector
      summary: Get a connector deployment
    delete:
      parameters:
        - name: id
          description: Id of the connector
          schema:
            type: string
          in: path
          required: true
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Deleted
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
          description: Auth token is invalid
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                404DeleteExample:
                  $ref: '#/components/examples/404DeleteExample'
          description: No kafka request with specified id exists
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500DeleteExample:
                  $ref: '#/components/examples/500DeleteExample'
          description: Unexpected error occurred
      security:
        - Bearer: [ ]
      operationId: deleteConnector
      summary: Delete a connector
    parameters:
      - $ref: "#/components/parameters/id"

  # Endpoints for data plane communications
  '/api/managed-services-api/v1/agent-clusters/{id}/status':
    put:
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        description: Cluster status update data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataPlaneClusterUpdateStatusRequest'
        required: true
      responses:
        '200':
          description: Cluster status is updated
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                400InvalidIdExample:
                  $ref: '#/components/examples/400InvalidIdExample'
          description: id value is not valid
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                404Example:
                  $ref: '#/components/examples/404Example'
          # This is deliberate to hide the endpoints for unauthorised users
          description: Auth token is not valid.
      security:
        - Bearer: [ ]
      operationId: updateAgentClusterStatus
      summary: Update the status of an agent cluster

  '/api/managed-services-api/v1/agent-clusters/{id}/kafkas/status':
    put:
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        description: Kafka clusters status update data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataPlaneKafkaStatusUpdateRequest'
        required: true
      responses:
        '200':
          description: Status is updated for Kafka clusters
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                400InvalidIdExample:
                  $ref: '#/components/examples/400InvalidIdExample'
          description: id value is not valid
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                404Example:
                  $ref: '#/components/examples/404Example'
          # This is deliberate to hide the endpoints for unauthorised users
          description: Auth token is not valid.
      security:
        - Bearer: [ ]
      operationId: updateKafkaClusterStatus
      summary: Update the status of Kafka clusters on an agent cluster



components:
  schemas:
    ObjectReference:
      type: object
      properties:
        id:
          type: string
        kind:
          type: string
        href:
          type: string
    List:
      required:
        - kind
        - page
        - size
        - total
        - items
      type: object
      properties:
        kind:
          type: string
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
    Error:
      allOf:
        - $ref: "#/components/schemas/ObjectReference"
        - type: object
          properties:
            code:
              type: string
            reason:
              type: string
            operation_id:
              type: string

    ConnectorType:
      description: >-
        Represents a connector type supported by the API
      required:
        - name
        - openAPIV3Schema
        - version
      allOf:
        - $ref: '#/components/schemas/ObjectReference'
        - type: object
          properties:
            name:
              description: Name of the connector type.
              type: string
            version:
              description: Version of the connector type.
              type: string
            description:
              description: A description of the connector.
              type: string
            json_schema:
              description: >-
                A json schema that can be used to validate a connectors
                connector_spec field.
              type: object # todo: replace with better type

    ConnectorTypeList:
      allOf:
        - $ref: '#/components/schemas/List'
        - type: object
          properties:
            items:
              type: array
              items:
                allOf:
                  - $ref: '#/components/schemas/ConnectorType'
    ConnectorList:
      allOf:
        - $ref: '#/components/schemas/List'
        - type: object
          properties:
            items:
              type: array
              items:
                allOf:
                  - $ref: '#/components/schemas/Connector'
    Connector:
      description: A connector holds the configuration to connect a Kafka topic to another system.
      allOf:
        - $ref: '#/components/schemas/ObjectReference'
        - type: object
          properties:

            metadata:
              type: object
              properties:
                kafka_id:
                  type: string
                owner:
                  type: string
                name:
                  type: string
                created_at:
                  format: date-time
                  type: string
                updated_at:
                  format: date-time
                  type: string

            deployment_location:
              type: object
              properties:
                cloud_provider:
                  type: string
                multi_az:
                  type: boolean
                region:
                  type: string

            connector_type_id:
              type: string
            connector_spec:
              type: object
            status:
              type: string

    DataPlaneClusterUpdateStatusRequest:
      # TODO are there any fields that should be required?
      # TODO are there any fields that should be nullable? (this is, a pointer in the resulting generated Go code)
      description: "Schema for the request to update a data plane cluster's status"
      type: object
      properties:
        conditions:
          description: "The cluster data plane conditions"
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              reason:
                type: string
              message:
                type: string
              status:
                type: string
              lastTransitionTime:
                type: string
                #format: date-time # enable this?? or just set it as pure plain string?
        total:
          type: object
          properties:
            ingressEgressThroughputPerSec:
              type: string #an example is "40Gi", a k8s quantity. Should we have some special format at openapi level?" this example also happens on other fields
            connections:
              type: integer # an example is 10000. Should we have some special format at openapi level? this example also happens on other fields
            dataRetentionSize:
              type: string
            partitions:
              type: integer
        remaining:
          type: object
          properties:
            # TODO 'total', 'remaining' attributes share the same properties so should we refactor it to a common schema?
            ingressEgressThroughputPerSec:
              type: string #an example is "40Gi", a k8s quantity. Should we have some special format at openapi level?" this example also happens on other fields
            connections:
              type: integer # an example is 10000. Should we have some special format at openapi level? this example also happens on other fields
            dataRetentionSize:
              type: string
            partitions:
              type: integer
        nodeInfo:
          type: object
          properties:
            ceiling:
              type: integer
            floor:
              type: integer
            current:
              type: integer
            currentWorkLoadMinimum:
              type: integer
        resizeInfo:
          type: object
          properties:
            nodeDelta:
              type: integer
            delta:
              type: object
              properties:
                ingressEgressThroughputPerSec:
                  type: string #an example is "40Gi", a k8s quantity. Should we have some special format at openapi level?" this example also happens on other fields
                connections:
                  type: integer # an example is 10000. Should we have some special format at openapi level? this example also happens on other fields
                dataRetentionSize:
                  type: string
                maxPartitions:
                  type: integer
      example:
        $ref: "#/components/examples/DataPlaneClusterUpdateStatusRequestExample"

    DataPlaneKafkaStatus:
      description: "Schema of the status object for a Kafka cluster"
      type: object
      properties:
        conditions:
          description: "The status conditions of a Kafka cluster"
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              reason:
                type: string
              message:
                type: string
              status:
                type: string
              lastTransitionTime:
                type: string
        # do we need this for now?
        capacity:
          description: "Capacity information of the data plane cluster"
          type: object
          properties:
            ingressEgressThroughputPerSec:
              type: string #example: 4Mi
            totalMaxConnections:
              type: integer #example: 500
            maxDataRetentionSize:
              type: string #example: 100Gi
            maxPartitions:
              type: integer #example: 100
            maxDataRetentionPeriod:
              type: string #example: P14D
        versions:
          description: "Version information related to a Kafka cluster"
          type: object
          properties:
            kafka:
              type: string
            strimzi:
              type: string

    DataPlaneKafkaStatusUpdateRequest:
      description: "Schema for the request to update the statuses of Kafka clusters from data plane"
      type: object
      additionalProperties:
        type: object
        $ref: '#/components/schemas/DataPlaneKafkaStatus'
      example:
        $ref: '#/components/examples/DataPlaneKafkaUpdateStatusRequestExample'

  parameters:
    id:
      name: id
      description: The id of record
      schema:
        type: string
      in: path
      required: true
    page:
      name: page
      in: query
      description: Page index
      required: false
      schema:
        type: string
      examples:
        page:
          value: "1"
    size:
      name: size
      in: query
      description: Number of items in each page
      required: false
      schema:
        type: string
      examples:
        size:
          value: "100"

  examples:
    DataPlaneClusterUpdateStatusRequestExample:
      value: {} # TODO fill this
    DataPlaneKafkaUpdateStatusRequestExample:
      value:
        1iSY6RQ3JKI8Q0OTmjQFd3ocFRg:
          conditions:
            - type: Ready
              reason: KafkaInstanceReady
              message: installing
              status: "False"
              lastTransitionTime: "2018-01-01T00:00:00Z"
          capacity:
            ingressEgressThroughputPerSec: 4Mi
            totalMaxConnections: 500
            maxDataRetentionSize: 100Gi
            maxPartitions: 100
            maxDataRetentionPeriod: P14D
          versions:
            kafka: 2.4.1
            strimzi: 0.21.2
    400DeletionExample:
      value:
        id: "103"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/103"
        code: "MGD-SERV-API-103"
        reason: "Synchronous action is not supported, use async=true parameter"
        operation_id: "1iWIimqGcrDuL61aUxIZqBTqNRa"
    400CreationExample:
      value:
        id: "103"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/103"
        code: "MGD-SERV-API-103"
        reason: "Synchronous action is not supported, use async=true parameter"
        operation_id: "1iWIimqGcrDuL61aUxIZqBTqNRa"
    400InvalidQueryExample:
      value:
        id: "203"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/23"
        code: "MGD-SERV-API-23"
        reason: "Failed to parse search query: Unable to list kafka requests for api_kafka_service: MGD-SERV-API-23: Failed to parse search query: Unsupported column name for search: 'id'. Supported column names are: region, name, cloud_provider, name, status. Query invalid: id = 123"
        operation_id: "1lWDGuybIrEnxrAem724gqkkiDv"
    400InvalidIdExample:
      value:
        id: "203"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/21"
        code: "MGD-SERV-API-21"
        reason: "Bad request"
        operation_id: "1lWDGuybIrEnxrAem724gqkkiDv"
    404Example:
      value:
        id: "404"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/7"
        code: "MGD-SERV-API-7"
        reason: "The requested resource doesn't exist"
    404DeleteExample:
      value:
        id: "7"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/7"
        code: "MGD-SERV-API-7"
        reason: "KafkaResource with id='1iK3duVYIvv5YvLlyz1mGR3JyqN' not found"
        operation_id: "1iYO7g2g6HTdUKUa2ksH82kQD3y"
    401Example:
      value:
        id: "11"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/11"
        code: "MGD-SERV-API-11"
        reason: "Unable to verify JWT token: Required authorization token not found"
        operation_id: "1iY3UhEhwmXBpWPfI2lNekpd4ZD"
    403Example:
      value:
        id: "4"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/4"
        code: "MGD-SERV-API-4"
        reason: "User 'foo-bar' is not authorized to access the service."
        operation_id: "1lY3UiEhznXBpWPfI2lNejpd4YC"
    403MaxAllowedInstanceReachedExample:
      value:
        id: "5"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/5"
        code: "MGD-SERV-API-5"
        reason: "User 'foo-bar' has reached a maximum number of 6 allowed instances."
        operation_id: "1lY3UiEkxnXBpVPeI2oNejd3XB"
    409NameConflictExample:
      value:
        id: "36"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/36"
        code: "MGD-SERV-API-36"
        reason: "Kafka cluster name is already used"
        operation_id: "6kY0UiEkzkXCzWPeI2oYehd3ED"
    500Example:
      value:
        id: "9"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/9"
        code: "MGD-SERV-API-9"
        reason: "Unspecified error"
        operation_id: "1ieELvF9jMQY6YghfM9gGRsHvEW"
    500DeleteExample:
      value:
        id: "9"
        kind: "Error"
        href: "/api/managed-services-api/v1/errors/9"
        code: "MGD-SERV-API-9"
        reason: "error deleting syncset: OCM-EX-9: failed to delete syncset: ext-serviceapi-1ix03lndlmq0qfc7sita5sljv8e
          for cluster id: 1g5d88q0lrcdv4g7alb7slfgnj3dhbsj%!(EXTRA *errors.Error=identifier
          is '404', code is 'CLUSTERS-MGMT-404' and operation identifier is '1g5or50viu07oealuehrkc26dgftj1ac':
          Cluster '1g5d88q0lrcdv4g7alb7slfgnj3dhbsj' not found)"
        operation_id: "1iYTsWry6nsqb2sNmFj5bXpD7Ca"
